"""Placeholder data used to lay out the portals.

The Collections, Sync & Reset and search screens still render from these
constants so they can be reviewed without a Drive connection, a Chroma store
or an embedding model.

Configuration is no longer mocked - it lives in the setting table and is read
through services/SettingService.py.
"""

STATS = {
    "embedded": "312",
    "source_files": "348",
    "converted_files": "312",
    "skipped_files": "36",
    "last_sync": "2h ago",
    "store_size": "48.2 MB",
}

DOCUMENTS = [
    ("1aB7xQfKm2LpZr9TnVdEs4YwHc0JgUiOe", "Docker\\Docker Commands Cheat Sheet", "image"),
    ("2cD8yRgLn3MqAs0UoWfFt5ZxId1KhVjPf", "Docker\\Docker General Notes", "doc"),
    ("3eF9zShMo4NrBt1VpXgGu6AyJe2LiWkQg", "Docker\\Installation Guides", "doc"),
    ("4gH0aTiNp5OsCu2WqYhHv7BzKf3MjXlRh", "Flutter\\Build\\Build", "doc"),
    ("5iJ1bUjOq6PtDv3XrZiIw8CaLg4NkYmSi", "Flutter\\App Icon\\Change Icon", "doc"),
    ("6kL2cVkPr7QuEw4YsAjJx9DbMh5OlZnTj", "Git\\Git Flow", "image"),
    ("7mN3dWlQs8RvFx5ZtBkKy0EcNi6PmAoUk", "Git\\Branch Rename", "doc"),
    ("8oP4eXmRt9SwGy6AuClLz1FdOj7QnBpVl", "Java\\Spring Boot Setup", "doc"),
    ("9qR5fYnSu0TxHz7BvDmMa2GePk8RoCqWm", "Java\\Spring Annotations", "doc"),
    ("0sT6gZoTv1UyIa8CwEnNb3HfQl9SpDrXn", "Java\\JPA, IOC, AOP, MVC", "doc"),
    ("1uV7hApUw2VzJb9DxFoOc4IgRm0TqEsYo", "Java\\Quartz\\Quartz", "doc"),
    ("2wX8iBqVx3WaKc0EyGpPd5JhSn1UrFtZp", "Java\\JavaMultiTreadingAndAsync\\ThreadExample1", "code"),
    ("3yZ9jCrWy4XbLd1FzHqQe6KiTo2VsGuAq", "Linux\\Linux General Notes", "doc"),
    ("4aB0kDsXz5YcMe2GaIrRf7LjUp3WtHvBr", "Linux\\SSH & SFTP\\SSH Tunnel", "doc"),
    ("5cD1lEtYa6ZdNf3HbJsSg8MkVq4XuIwCs", "Linux\\SSH & SFTP\\SSH with Private Key", "doc"),
    ("6eF2mFuZb7AeOg4IcKtTh9NlWr5YvJxDt", "Linux\\Firewall", "doc"),
    ("7gH3nGvAc8BfPh5JdLuUi0OmXs6ZwKyEu", "Linux\\Installations\\Install docker", "doc"),
    ("8iJ4oHwBd9CgQi6KeMvVj1PnYt7AxLzFv", "Linux\\Linux Path Cheatsheet", "image"),
    ("9kL5pIxCe0DhRj7LfNwWk2QoZu8ByMaGw", "Networking\\Networking", "doc"),
    ("0mN6qJyDf1EiSk8MgOxXl3RpAv9CzNbHx", "Networking\\8 Popular Network Protocols", "image"),
    ("1oP7rKzEg2FjTl9NhPyYm4SqBw0DaOcIy", "Networking\\OSI Layers and Protocols Example", "image"),
    ("2qR8sLaFh3GkUm0OiQzZn5TrCx1EbPdJz", "Nginx\\Nginx", "doc"),
    ("3sT9tMbGi4HlVn1PjRaAo6UsDy2FcQeKa", "Nginx\\Load Balancer", "doc"),
    ("4uV0uNcHj5ImWo2QkSbBp7VtEz3GdRfLb", "Nginx\\Proxy", "doc"),
    ("5wX1vOdIk6JnXp3RlTcCq8WuFa4HeSgMc", "Node.js\\Node.js", "doc"),
    ("6yZ2wPeJl7KoYq4SmUdDr9XvGb5IfThNd", "Node.js\\Node\\server", "code"),
    ("7aB3xQfKm8LpZr5TnVeEs0YwHc6JgUiOe", "Python\\Python Notes\\Async\\Asyncio", "doc"),
    ("8cD4yRgLn9MqAs6UoWfFt1ZxId7KhVjPf", "Python\\Python Notes\\Threading\\testThreading_1", "code"),
    ("9eF5zShMo0NrBt7VpXgGu2AyJe8LiWkQg", "Python\\Python Notes\\Pandas\\Pandas", "doc"),
    ("0gH6aTiNp1OsCu8WqYhHv3BzKf9MjXlRh", "Python\\VectorDB\\VectorDB Libraries Installation", "doc"),
    ("1iJ7bUjOq2PtDv9XrZiIw4CaLg0NkYmSi", "SQL\\Postgres", "doc"),
    ("2kL8cVkPr3QuEw0YsAjJx5DbMh1OlZnTj", "SQL\\MSSQL", "doc"),
    ("3mN9dWlQs4RvFx1ZtBkKy6EcNi2PmAoUk", "Redis\\Commands Cheat Sheet", "doc"),
    ("4oP0eXmRt5SwGy2AuClLz7FdOj3QnBpVl", "Security\\nmap\\nmap cheat sheet page1", "image"),
    ("5qR1fYnSu6TxHz3BvDmMa8GePk4RoCqWm", "Security\\Study Paths", "doc"),
    ("6sT2gZoTv7UyIa4CwEnNb9HfQl5SpDrXn", "VueJs\\Setup", "doc"),
    ("7uV3hApUw8VzJb5DxFoOc0IgRm6TqEsYo", "VueJs\\Vue Nonce-based CSP", "doc"),
    ("8wX4iBqVx9WaKc6EyGpPd1JhSn2UrFtZp", "Windows Commands\\Windows Commands", "doc"),
]

# Ordered by distance the way TextEmbedderService.query() returns them.
SEARCH_RESULTS = [
    {
        "id": "4aB0kDsXz5YcMe2GaIrRf7LjUp3WtHvBr",
        "label": "Linux\\SSH & SFTP\\SSH Tunnel",
        "kind": "doc",
        "distance": 0.2841,
        "modified": "2026-05-18 09:41",
        "snippet": "Local port forwarding: ssh -L 8080:localhost:80 user@host. Reverse tunnel "
                   "exposes a local service on the remote side with -R ...",
    },
    {
        "id": "5cD1lEtYa6ZdNf3HbJsSg8MkVq4XuIwCs",
        "label": "Linux\\SSH & SFTP\\SSH with Private Key",
        "kind": "doc",
        "distance": 0.3517,
        "modified": "2026-04-02 16:07",
        "snippet": "Generate the pair with ssh-keygen -t ed25519, copy the public half to "
                   "~/.ssh/authorized_keys and tighten permissions to 600 ...",
    },
    {
        "id": "6eF2mFuZb7AeOg4IcKtTh9NlWr5YvJxDt",
        "label": "Linux\\Firewall",
        "kind": "doc",
        "distance": 0.4880,
        "modified": "2026-03-27 11:22",
        "snippet": "firewall-cmd --add-port=22/tcp --permanent then reload. Check the active "
                   "zone before opening anything on a public interface ...",
    },
    {
        "id": "8iJ4oHwBd9CgQi6KeMvVj1PnYt7AxLzFv",
        "label": "Linux\\Linux Path Cheatsheet",
        "kind": "image",
        "distance": 0.6123,
        "modified": "2026-01-14 20:55",
        "snippet": "-----img start----- /etc holds configuration, /var holds variable state, "
                   "/opt holds optional add-on packages ----- img end -----",
    },
    {
        "id": "0mN6qJyDf1EiSk8MgOxXl3RpAv9CzNbHx",
        "label": "Networking\\8 Popular Network Protocols",
        "kind": "image",
        "distance": 0.7402,
        "modified": "2025-11-08 13:30",
        "snippet": "HTTP, HTTPS, FTP, SMTP, SSH, DNS, DHCP, TCP - what each one is for and "
                   "which OSI layer it sits on ...",
    },
]

SEARCH_HISTORY = [
    ("ssh tunnel port forwarding", "2 min ago", 5),
    ("spring boot annotations", "18 min ago", 5),
    ("docker compose volumes", "1 hour ago", 5),
    ("chroma persistent client", "Yesterday", 4),
    ("nginx reverse proxy config", "Yesterday", 5),
    ("pytesseract image to string", "2 days ago", 3),
    ("quartz scheduler tables", "2 days ago", 5),
    ("mammoth convert docx to html", "5 days ago", 2),
]

SYNC_SUMMARY = [
    ("Added", "6", "success"),
    ("Updated", "11", "info"),
    ("Removed", "2", "warning"),
    ("Unchanged", "293", "neutral"),
]

# One row per file, shaped the way SyncPlannerService.scan() will return them.
#
#   added       on Drive, not in the collection yet
#   updated     Drive modifiedTime moved since we embedded it
#   stale_local the mirror file was edited but Drive's timestamp did not move
#   unchanged   nothing to do
#   removed     in the collection, gone from Drive - no local file at all
#   no_drive_id sits in the mirror but is not on Drive, so it can never embed
#   no_source   on Drive, but nothing local to convert
#   unsupported an extension the converter skips
SCAN_CHANGES = [
    {"key": "Docker\\Docker General Notes", "kind": "doc", "status": "updated",
     "document_id": "2cD8yRgLn3MqAs0UoWfFt5ZxId1KhVjPf", "needs_conversion": True,
     "drive_modified": "2026-08-14 09:12", "stored_modified": "2026-07-01 11:03"},
    {"key": "Docker\\Installation Guides", "kind": "doc", "status": "unchanged",
     "document_id": "3eF9zShMo4NrBt1VpXgGu6AyJe2LiWkQg", "needs_conversion": False,
     "drive_modified": "2026-05-22 14:40", "stored_modified": "2026-05-22 14:40"},
    {"key": "Docker\\Docker Commands Cheat Sheet", "kind": "image", "status": "unchanged",
     "document_id": "1aB7xQfKm2LpZr9TnVdEs4YwHc0JgUiOe", "needs_conversion": False,
     "drive_modified": "2026-02-11 08:15", "stored_modified": "2026-02-11 08:15"},
    {"key": "Docker\\Compose Volumes", "kind": "doc", "status": "added",
     "document_id": "9zA1bC2dE3fG4hI5jK6lM7nO8pQ9rS0tU", "needs_conversion": True,
     "drive_modified": "2026-08-15 07:58", "stored_modified": None},
    {"key": "Flutter\\Build\\Build", "kind": "doc", "status": "unchanged",
     "document_id": "4gH0aTiNp5OsCu2WqYhHv7BzKf3MjXlRh", "needs_conversion": False,
     "drive_modified": "2026-04-09 17:26", "stored_modified": "2026-04-09 17:26"},
    {"key": "Flutter\\App Icon\\Change Icon", "kind": "doc", "status": "unchanged",
     "document_id": "5iJ1bUjOq6PtDv3XrZiIw8CaLg4NkYmSi", "needs_conversion": False,
     "drive_modified": "2026-04-09 17:31", "stored_modified": "2026-04-09 17:31"},
    {"key": "Git\\Git Flow", "kind": "image", "status": "stale_local",
     "document_id": "6kL2cVkPr7QuEw4YsAjJx9DbMh5OlZnTj", "needs_conversion": True,
     "drive_modified": "2026-03-14 10:02", "stored_modified": "2026-03-14 10:02"},
    {"key": "Git\\Branch Rename", "kind": "doc", "status": "unchanged",
     "document_id": "7mN3dWlQs8RvFx5ZtBkKy0EcNi6PmAoUk", "needs_conversion": False,
     "drive_modified": "2026-01-30 12:48", "stored_modified": "2026-01-30 12:48"},
    {"key": "Git\\Rebase vs Merge", "kind": "doc", "status": "added",
     "document_id": "8tU9vW0xY1zA2bC3dE4fG5hI6jK7lM8nO", "needs_conversion": True,
     "drive_modified": "2026-08-15 08:41", "stored_modified": None},
    {"key": "Java\\Spring Boot Setup", "kind": "doc", "status": "updated",
     "document_id": "8oP4eXmRt9SwGy6AuClLz1FdOj7QnBpVl", "needs_conversion": True,
     "drive_modified": "2026-08-13 16:20", "stored_modified": "2026-06-18 09:55"},
    {"key": "Java\\Spring Annotations", "kind": "doc", "status": "unchanged",
     "document_id": "9qR5fYnSu0TxHz7BvDmMa2GePk8RoCqWm", "needs_conversion": False,
     "drive_modified": "2026-06-18 09:57", "stored_modified": "2026-06-18 09:57"},
    {"key": "Java\\JPA, IOC, AOP, MVC", "kind": "doc", "status": "unchanged",
     "document_id": "0sT6gZoTv1UyIa8CwEnNb3HfQl9SpDrXn", "needs_conversion": False,
     "drive_modified": "2026-06-18 10:02", "stored_modified": "2026-06-18 10:02"},
    {"key": "Java\\Quartz\\Quartz", "kind": "doc", "status": "updated",
     "document_id": "1uV7hApUw2VzJb9DxFoOc4IgRm0TqEsYo", "needs_conversion": True,
     "drive_modified": "2026-08-12 11:34", "stored_modified": "2026-05-02 15:19"},
    {"key": "Java\\JavaMultiTreadingAndAsync\\ThreadExample1", "kind": "code", "status": "unchanged",
     "document_id": "2wX8iBqVx3WaKc0EyGpPd5JhSn1UrFtZp", "needs_conversion": False,
     "drive_modified": "2025-12-04 19:11", "stored_modified": "2025-12-04 19:11"},
    {"key": "Linux\\Linux General Notes", "kind": "doc", "status": "updated",
     "document_id": "3yZ9jCrWy4XbLd1FzHqQe6KiTo2VsGuAq", "needs_conversion": True,
     "drive_modified": "2026-08-14 21:07", "stored_modified": "2026-07-29 08:23"},
    {"key": "Linux\\SSH & SFTP\\SSH Tunnel", "kind": "doc", "status": "unchanged",
     "document_id": "4aB0kDsXz5YcMe2GaIrRf7LjUp3WtHvBr", "needs_conversion": False,
     "drive_modified": "2026-05-18 09:41", "stored_modified": "2026-05-18 09:41"},
    {"key": "Linux\\SSH & SFTP\\SSH with Private Key", "kind": "doc", "status": "unchanged",
     "document_id": "5cD1lEtYa6ZdNf3HbJsSg8MkVq4XuIwCs", "needs_conversion": False,
     "drive_modified": "2026-04-02 16:07", "stored_modified": "2026-04-02 16:07"},
    {"key": "Linux\\Firewall", "kind": "doc", "status": "stale_local",
     "document_id": "6eF2mFuZb7AeOg4IcKtTh9NlWr5YvJxDt", "needs_conversion": True,
     "drive_modified": "2026-03-27 11:22", "stored_modified": "2026-03-27 11:22"},
    {"key": "Linux\\Installations\\Install docker", "kind": "doc", "status": "unchanged",
     "document_id": "7gH3nGvAc8BfPh5JdLuUi0OmXs6ZwKyEu", "needs_conversion": False,
     "drive_modified": "2026-02-19 13:05", "stored_modified": "2026-02-19 13:05"},
    {"key": "Linux\\Linux Path Cheatsheet", "kind": "image", "status": "unchanged",
     "document_id": "8iJ4oHwBd9CgQi6KeMvVj1PnYt7AxLzFv", "needs_conversion": False,
     "drive_modified": "2026-01-14 20:55", "stored_modified": "2026-01-14 20:55"},
    {"key": "Linux\\Systemd Units", "kind": "doc", "status": "no_source",
     "document_id": "1pQ2rS3tU4vW5xY6zA7bC8dE9fG0hI1jK", "needs_conversion": False,
     "drive_modified": "2026-07-11 09:33", "stored_modified": None},
    {"key": "Networking\\Networking", "kind": "doc", "status": "unchanged",
     "document_id": "9kL5pIxCe0DhRj7LfNwWk2QoZu8ByMaGw", "needs_conversion": False,
     "drive_modified": "2026-03-02 10:14", "stored_modified": "2026-03-02 10:14"},
    {"key": "Networking\\8 Popular Network Protocols", "kind": "image", "status": "unchanged",
     "document_id": "0mN6qJyDf1EiSk8MgOxXl3RpAv9CzNbHx", "needs_conversion": False,
     "drive_modified": "2025-11-08 13:30", "stored_modified": "2025-11-08 13:30"},
    {"key": "Networking\\OSI Layers and Protocols Example", "kind": "image", "status": "unchanged",
     "document_id": "1oP7rKzEg2FjTl9NhPyYm4SqBw0DaOcIy", "needs_conversion": False,
     "drive_modified": "2025-11-08 13:34", "stored_modified": "2025-11-08 13:34"},
    {"key": "Nginx\\Nginx", "kind": "doc", "status": "unchanged",
     "document_id": "2qR8sLaFh3GkUm0OiQzZn5TrCx1EbPdJz", "needs_conversion": False,
     "drive_modified": "2026-06-01 08:09", "stored_modified": "2026-06-01 08:09"},
    {"key": "Nginx\\Load Balancer", "kind": "doc", "status": "unchanged",
     "document_id": "3sT9tMbGi4HlVn1PjRaAo6UsDy2FcQeKa", "needs_conversion": False,
     "drive_modified": "2026-06-01 08:12", "stored_modified": "2026-06-01 08:12"},
    {"key": "Nginx\\Proxy", "kind": "doc", "status": "updated",
     "document_id": "4uV0uNcHj5ImWo2QkSbBp7VtEz3GdRfLb", "needs_conversion": True,
     "drive_modified": "2026-08-14 15:52", "stored_modified": "2026-06-01 08:15"},
    {"key": "Node.js\\Node.js", "kind": "doc", "status": "unchanged",
     "document_id": "5wX1vOdIk6JnXp3RlTcCq8WuFa4HeSgMc", "needs_conversion": False,
     "drive_modified": "2026-02-27 18:44", "stored_modified": "2026-02-27 18:44"},
    {"key": "Node.js\\Node\\server", "kind": "code", "status": "unchanged",
     "document_id": "6yZ2wPeJl7KoYq4SmUdDr9XvGb5IfThNd", "needs_conversion": False,
     "drive_modified": "2026-02-27 18:47", "stored_modified": "2026-02-27 18:47"},
    {"key": "Python\\Python Notes\\Async\\Asyncio", "kind": "doc", "status": "updated",
     "document_id": "7aB3xQfKm8LpZr5TnVeEs0YwHc6JgUiOe", "needs_conversion": True,
     "drive_modified": "2026-08-15 06:30", "stored_modified": "2026-07-20 12:41"},
    {"key": "Python\\Python Notes\\Threading\\testThreading_1", "kind": "code", "status": "unchanged",
     "document_id": "8cD4yRgLn9MqAs6UoWfFt1ZxId7KhVjPf", "needs_conversion": False,
     "drive_modified": "2026-07-20 12:44", "stored_modified": "2026-07-20 12:44"},
    {"key": "Python\\Python Notes\\Pandas\\Pandas", "kind": "doc", "status": "unchanged",
     "document_id": "9eF5zShMo0NrBt7VpXgGu2AyJe8LiWkQg", "needs_conversion": False,
     "drive_modified": "2026-07-20 12:49", "stored_modified": "2026-07-20 12:49"},
    {"key": "Python\\VectorDB\\VectorDB Libraries Installation", "kind": "doc", "status": "unchanged",
     "document_id": "0gH6aTiNp1OsCu8WqYhHv3BzKf9MjXlRh", "needs_conversion": False,
     "drive_modified": "2026-05-06 20:18", "stored_modified": "2026-05-06 20:18"},
    {"key": "Python\\Scratch\\untitled notes", "kind": "doc", "status": "no_drive_id",
     "document_id": None, "needs_conversion": True,
     "drive_modified": None, "stored_modified": None},
    {"key": "SQL\\Postgres", "kind": "doc", "status": "unchanged",
     "document_id": "1iJ7bUjOq2PtDv9XrZiIw4CaLg0NkYmSi", "needs_conversion": False,
     "drive_modified": "2026-04-25 09:26", "stored_modified": "2026-04-25 09:26"},
    {"key": "SQL\\MSSQL", "kind": "doc", "status": "unchanged",
     "document_id": "2kL8cVkPr3QuEw0YsAjJx5DbMh1OlZnTj", "needs_conversion": False,
     "drive_modified": "2026-04-25 09:31", "stored_modified": "2026-04-25 09:31"},
    {"key": "Redis\\Commands Cheat Sheet", "kind": "doc", "status": "removed",
     "document_id": "3mN9dWlQs4RvFx1ZtBkKy6EcNi2PmAoUk", "needs_conversion": False,
     "drive_modified": None, "stored_modified": "2026-01-08 11:57"},
    {"key": "Security\\nmap\\nmap cheat sheet page1", "kind": "image", "status": "unchanged",
     "document_id": "4oP0eXmRt5SwGy2AuClLz7FdOj3QnBpVl", "needs_conversion": False,
     "drive_modified": "2025-10-19 15:22", "stored_modified": "2025-10-19 15:22"},
    {"key": "Security\\Study Paths", "kind": "doc", "status": "removed",
     "document_id": "5qR1fYnSu6TxHz3BvDmMa8GePk4RoCqWm", "needs_conversion": False,
     "drive_modified": None, "stored_modified": "2025-10-19 15:28"},
    {"key": "VueJs\\Setup", "kind": "doc", "status": "unchanged",
     "document_id": "6sT2gZoTv7UyIa4CwEnNb9HfQl5SpDrXn", "needs_conversion": False,
     "drive_modified": "2026-03-19 07:48", "stored_modified": "2026-03-19 07:48"},
    {"key": "VueJs\\Vue Nonce-based CSP", "kind": "doc", "status": "unchanged",
     "document_id": "7uV3hApUw8VzJb5DxFoOc0IgRm6TqEsYo", "needs_conversion": False,
     "drive_modified": "2026-03-19 07:53", "stored_modified": "2026-03-19 07:53"},
    {"key": "VueJs\\Pinia Store", "kind": "doc", "status": "added",
     "document_id": "2lM3nO4pQ5rS6tU7vW8xY9zA0bC1dE2fG", "needs_conversion": True,
     "drive_modified": "2026-08-15 09:04", "stored_modified": None},
    {"key": "Windows Commands\\Windows Commands", "kind": "doc", "status": "unchanged",
     "document_id": "8wX4iBqVx9WaKc6EyGpPd1JhSn2UrFtZp", "needs_conversion": False,
     "drive_modified": "2026-01-22 16:38", "stored_modified": "2026-01-22 16:38"},
    {"key": "Windows Commands\\WSL Setup", "kind": "doc", "status": "added",
     "document_id": "3hI4jK5lM6nO7pQ8rS9tU0vW1xY2zA3bC", "needs_conversion": True,
     "drive_modified": "2026-08-15 09:21", "stored_modified": None},
    {"key": "Format PC\\Tools\\rufus-4.1", "kind": "unknown", "status": "unsupported",
     "document_id": None, "needs_conversion": False,
     "drive_modified": "2025-09-02 10:00", "stored_modified": None},
    {"key": "Format PC\\Tools\\ventoy-1.0.99", "kind": "unknown", "status": "unsupported",
     "document_id": None, "needs_conversion": False,
     "drive_modified": "2025-09-02 10:04", "stored_modified": None},
    {"key": "Certificates\\AWS SAA Certificate", "kind": "unknown", "status": "unsupported",
     "document_id": None, "needs_conversion": False,
     "drive_modified": "2025-08-14 09:12", "stored_modified": None},
]

# Header strip shown once a scan has finished.
SCAN_STATS = {
    "scanned_at": "10:24:01",
    "duration": "6s",
    "walked": "348",
    "drive_files": "346",
    "embedded": "312",
}

SYNC_LOG = [
    ("10:24:01", "INFO", "Syncing collection"),
    ("10:24:01", "INFO", "Start syncing files"),
    ("10:24:03", "INFO", "Converting (changed): resources\\files\\Docker\\Docker General Notes.docx"),
    ("10:24:06", "INFO", "Converting (changed): resources\\files\\Nginx\\Proxy.docx"),
    ("10:24:07", "INFO", "Skipping (unchanged): resources\\files\\SQL\\Postgres.docx"),
    ("10:24:09", "WARN", "Skip unknown file: resources\\files\\Format PC\\Tools\\rufus-4.1.exe"),
    ("10:24:12", "INFO", "File sync completed - converted: 17, skipped: 331"),
    ("10:24:13", "INFO", "Fetching Drive file ids"),
    ("10:24:21", "INFO", "Upserting 17 documents into my_knowledge_drive"),
    ("10:24:24", "INFO", "Deleting 2 documents no longer on Drive"),
    ("10:24:25", "DONE", "Sync completed - added: 6, updated: 11, removed: 2, unchanged: 293"),
]

RESET_LOG = [
    ("09:02:11", "INFO", "Reseting collection"),
    ("09:02:11", "WARN", "Clearing: resources\\converted_files"),
    ("09:02:14", "INFO", "Start converting files"),
    ("09:04:52", "INFO", "Total converted files: 348"),
    ("09:04:53", "WARN", "Deleting collection my_knowledge_drive"),
    ("09:04:55", "INFO", "Start embedding files"),
    ("09:07:38", "DONE", "Total embedded files: 312"),
]

